server:
  port: @server.port@
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/exeStudy?zeroDateTimeBehavior=convertToNull&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ENC(cG6OyGw9pOW1/57c80aO+A==)
    password: ENC(cG6OyGw9pOW1/57c80aO+A==)
jasypt:
  encryptor:
    password: 31e1ea1269204fc1a2102f40d9b7a33a
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

mybatis:
  type-aliases-package: com.zyp.interview.demo     # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启MyBatis日志sql打印

mapper:
  not-empty: false
  identity: MYSQL
#分页插件配置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true


